# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-release-nginx-ingress-controller
#   namespace: nginx-ingress
# spec:
#   template:
#     spec:
#       serviceAccountName: nginx-ingress
#       containers:
#       - image: nginx/nginx-ingress:3.6.0
#         imagePullPolicy: IfNotPresent
#         name: nginx-ingress
#         ports:
#         - name: http
#           containerPort: 85
#         - name: https
#           containerPort: 443
#         - name: readiness-port
#           containerPort: 8081
#         - name: prometheus
#           containerPort: 9113
#         readinessProbe:
#           httpGet:
#             path: /nginx-ready
#             port: readiness-port
#           periodSeconds: 1
#         securityContext: