apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
  creationTimestamp: "2024-07-06T13:11:55Z"
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-29.0.0
  name: traefik
  namespace: traefik
  resourceVersion: "10298"
  uid: 01b70d56-9f48-4267-a1d1-aba4b5b7f6f8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.90.245
  clusterIPs:
  - 10.101.90.245
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 15728
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 6326
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
