{{- if eq (.Values.dohProxy.enabled | toString) "true" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dohProxy.serviceName }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.dohProxy.serviceName }}
  replicas: {{ .Values.dohProxy.deployment.replicaCount }}
  template:
    metadata:
      labels:
        run: {{ .Values.dohProxy.serviceName }}
    spec:
      containers:
        - name: {{ .Values.dohProxy.serviceName }}
          image: {{ .Values.dohProxy.deployment.image.repository }}
          command:
            [
              "doh-proxy", 
              "--listen-address={{ tpl (.Values.dohProxy.config.listenAddress) . }}",
              "--server-address={{ tpl (.Values.dohProxy.config.serverAddress) . }}"
            ]
          ports:
            - containerPort: {{ .Values.dohProxy.service.port }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dohProxy.serviceName }}
  labels:
    run: {{ .Values.dohProxy.serviceName }}
spec:
  type:  {{ .Values.dohProxy.service.type }}
  ports:
    - name: doh-proxy
      port: {{ .Values.dohProxy.service.port }}
      protocol: TCP
  selector:
    run: {{ .Values.dohProxy.serviceName }}
{{- end }}
