{{- if eq (.Values.tcp.enabled | toString) "true" -}}
{{- if eq (.Values.ingress.class | toString) "haproxy" -}}
apiVersion: ingress.v1.haproxy.org/v1
kind: TCP
metadata:
  name: services-tcp
spec:
  {{- range .Values.tcp.services }}
  - name: {{ .name }}
    frontend:
      name: "{{ .name }}-frontend"
      tcplog: true
      binds:
        - name: "{{ .name }}-bind"
          port:  {{ .frontend.port }}
          {{- if .frontend.ssl }}
          ssl: {{ .frontend.ssl }}
          ssl_certificate: {{ .frontend.ssl_certificate }}
          {{- end }}
    service:
      name: "{{ .backend.service }}"
      port: {{ .backend.port }}
  {{- end }}
{{- end }}
{{- end }}
