# kubectl patch deploy -n kong kong-gateway --patch-file 
---
spec:
  template:
    spec:
      containers:
      - name: proxy
        env:
        - name: KONG_STREAM_LISTEN
          value: 0.0.0.0:9000, 0.0.0.0:9443 ssl, 0.0.0.0:853 ssl
        - name: KONG_NGINX_STREAM_SSL_PREREAD
          value: "on"
        - name: KONG_LOG_LEVEL
          value: info
        ports:
        #
        - containerPort: 853
          name: stream853
          protocol: TCP
