# kubectl patch deploy -n kong kong-gateway --patch-file 
---
spec:
  template:
    spec:
      containers:
      - name: proxy
        env:
        - name: KONG_STREAM_LISTEN
          value: 0.0.0.0:9000, 0.0.0.0:9443 ssl,  0.0.0.0:853 ssl, 0.0.0.0:5353
        ports:
        - containerPort: 9000
          name: stream9000
          protocol: TCP
        - containerPort: 9443
          name: stream9443
          protocol: TCP
        #
        - containerPort: 853
          name: stream853
          protocol: TCP

        - containerPort: 5353
          name: stream5353
          protocol: TCP